maximum_length_name: 50
maximum_length_email: 255
max_content: 140
minimum_length_pass: 6
maximum_length_phone: 15
size_gravatar: 80
subjects_per_page: 12
users_per_page: 12
questions_per_page: 15
exams_per_page: 15
maximum_length_question_content: 400
maximum_length_subject_name: 20 
